### ISSUE TITLE
Issues compiling on CentOS with jansson

### ISSUE THREAD

**Issue by networkmaster** [pmacct/pmacct#318]
Hey all,

Been pulling my hair out trying to get pmacct compiled on CentOS 7 with jansson enabled. 
Pretty sure i have all required libraries, but i get this error:

  _
Snip
CC       libpmbgp_la-bgp_logdump.lo
bgp_logdump.c: In function 'bgp_peer_log_msg':
bgp_logdump.c:207:59: error: 'writer_pid' undeclared (first use in this function)
       add_writer_name_and_pid_json(obj, config.proc_name, writer_pid);
                                                           ^
bgp_logdump.c:207:59: note: each undeclared identifier is reported only once for each function it appears in
gmake[2]: *** [libpmbgp_la-bgp_logdump.lo] Error 1
snip
_

I get this for 3 files:
src/bgp/bgp_logdump.c (line 207)
src/bmp/bmp_logdump.c (line 121)
src/telemetry/telemetry_logdump.c (line 119)

If i edit each of these files and change this line:
#if defined(WITH_KAFKA) || defined(WITH_RABBITMQ)
to
#if defined(WITH_KAFKA) || defined(WITH_RABBITMQ) || defined(WITH_JANSSON)

It gets around it, but i get more errors (below)

Not sure if this is a permanent fix, or just a "hack" work around - guidance appreciated and how to fix the below. I'm not really a C guy, so the rest is a bit above me

Kernel:
Linux localhost.localdomain 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CentOS: CentOS Linux release 7.6.1810 (Core) 
GCC: gcc-4.8.5-36.el7_6.2.x86_64
libgcc-4.8.5-36.el7_6.2.x86_64

Running the latest clone from the git repo 

_gmake[2]: Entering directory `/opt/pmacct/src/isis'
  CC       libpmisis_la-isis.lo
isis.c: In function 'skinny_isis_daemon':
isis.c:150:3: warning: pointer targets in passing argument 2 of 'area_net_title' differ in signedness [-Wpointer-sign]
   if (config.nfacctd_isis_net) area_net_title(area, config.nfacctd_isis_net);
   ^
In file included from isis.c:46:0:
isisd.h:126:12: note: expected 'const u_char *' but argument is of type 'char *'
 extern int area_net_title(struct isis_area *, const u_char *);
            ^
isis.c: In function 'isis_pdu_runner':
isis.c:266:8: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
  ssnpa = pptrs.packet_ptr;
        ^
isis.c:271:2: warning: pointer targets in passing argument 2 of 'isis_handle_pdu' differ in signedness [-Wpointer-sign]
  isis_handle_pdu (circuit, ssnpa);
  ^
In file included from isis.c:49:0:
isis_pdu.h:236:12: note: expected 'u_char *' but argument is of type 'char *'
 extern int isis_handle_pdu (struct isis_circuit *, u_char *);
            ^
isis.c: In function 'igp_daemon_map_validate':
isis.c:661:7: warning: pointer targets in passing argument 1 of 'igp_daemon_map_handle_lsp_id' differ in signedness [-Wpointer-sign]
       if (igp_daemon_map_handle_lsp_id(lsp_hdr->lsp_id, &entry->node)) return;
       ^
In file included from isis.c:26:0:
isis.h:92:12: note: expected 'char *' but argument is of type 'u_char *'
 extern int igp_daemon_map_handle_lsp_id(char *, struct host_addr *);
            ^
isis.c:793:2: warning: pointer targets in passing argument 1 of 'pcap_dump' differ in signedness [-Wpointer-sign]
  pcap_dump((char *) idmm_fd, &phdr, isis_dgram);
  ^
In file included from /usr/include/pcap.h:45:0,
                 from ./../pmacct.h:30,
                 from isis.c:23:
/usr/include/pcap/pcap.h:419:6: note: expected 'u_char *' but argument is of type 'char *'
 void pcap_dump(u_char *, const struct pcap_pkthdr *, const u_char *);
      ^
isis.c:793:2: warning: pointer targets in passing argument 3 of 'pcap_dump' differ in signedness [-Wpointer-sign]
  pcap_dump((char *) idmm_fd, &phdr, isis_dgram);
  ^
In file included from /usr/include/pcap.h:45:0,
                 from ./../pmacct.h:30,
                 from isis.c:23:
/usr/include/pcap/pcap.h:419:6: note: expected 'const u_char *' but argument is of type 'char *'
 void pcap_dump(u_char *, const struct pcap_pkthdr *, const u_char *);
      ^
  CC       libpmisis_la-checksum.lo
_

**Comment by paololucente** [comment]
Hi Alek,

Can you please share your 'configure' command-line (ie. "./configure --enable-jansson [ .. ]") and say which version are you trying to compile? Is it code from GitHub master or some specific version?

Paolo

**Comment by networkmaster** [comment]
Hey Paolo,

Compiling from git that i pulled down mid way through last week.

Configure command:
./configure --sysconfdir=/etc --enable-l2 --enable-debug --enable-plabel --enable-64bit --enable-jansson

Version i managed to get compiled (with the errors mentioned)
nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20190910-00)

Arguments:
 '--sysconfdir=/etc' '--enable-l2' '--enable-debug' '--enable-plabel' '--enable-64bit' '--enable-jansson' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

**Comment by paololucente** [comment]
Hey Alek, it should be resolved after the latest commits. Can you please give it a try and let me know it now compiles fine for you? Paolo PS: in your second message you say about several messages despite which all compiles fine; those are warnings, not errors: they are known and being worked on but nothing to worry about.

**Comment by networkmaster** [comment]
Yep, worked first go, thanks Paolo
The warnings are still present, thanks for confirming they are known issue
