### ISSUE TITLE
nfacctd not resolving networks_file

### ISSUE THREAD

**Issue by fernandolcx** [pmacct/pmacct#338]
I'm using version `1.7.4-git (20191031-00)` and I'm following the tutorial at http://www.pmacct.net/docs/cacti.html to plot graphs on Cacti.

I was expecing output from `pmacct -s -p /tmp/in.pipe` to be like:
```
DST_IP                                         PACKETS               BYTES
0.0.0.0                                        5881085               6126431640
172.16.0.0                                     41                    8077
10.0.0.0                                       242                   98487
192.168.0.0                                    1077                  68377
100.64.0.0                                     876                   440861
```

But got this instead:
```
DST_NET                                        PACKETS               BYTES
0.0.0.0                                        623545                693612514
```

I can, however, get expected output when using version `1.5.2 (20150907-00)`, installed from Bionic repositories via `apt-get`.

**nfacctd.conf**:
```
plugins: memory[in], memory[out]
aggregate[in]: dst_net
aggregate[out]: src_net

networks_file: /home/lab/networks.lst
! networks_file_no_lpm: true
! nfacctd_as: file
! networks_no_mask_if_zero: true

imt_path[in]: /tmp/in.pipe
imt_path[out]: /tmp/out.pipe
```
note: none of the above commented options solves the problem.

**networks.lst**:
```
100.64.0.0/10
10.0.0.0/8
192.168.0.0/16
172.16.0.0/12
```

Any idea what I'm missing?
Thanks in advance.

**Comment by paololucente** [comment]
Hi Fernando ( @fernandolcx ), thanks for reporting this. In principle all looks good, let me try to reproduce your issue. Could you please post the output of "nfacctd -V"? Paolo

**Comment by fernandolcx** [comment]
> Hi Fernando ( @fernandolcx ), thanks for reporting this. In principle all looks good, let me try to reproduce your issue. Could you please post the output of "nfacctd -V"? Paolo

```
NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191031-00)

Arguments:
 '--enable-plabel' '--enable-pgsql' '--enable-rabbitmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-avro' '--enable-ndpi' '--enable-nflog' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.9.1 (with TPACKET_V3)
PostgreSQL 120000
rabbimq-c 0.9.0
rdkafka 0.11.6
jansson 2.12
MaxmindDB 1.3.2
avro-c
nDPI 2.6.0
netfilter_log

System:
Linux 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64

Compiler:
gcc 9.2.1
```

**Comment by fernandolcx** [comment]
some additional info:

Installed dependencies:
```
apt-get install \
libpcap-dev \
pkg-config \
libtool \
autoconf \
automake \
bash \
zlib1g-dev \
libpq-dev \
librabbitmq-dev \
librdkafka-dev \
libmaxminddb-dev \
libjansson-dev \
libavro-dev \
libndpi-dev \
libnetfilter-log-dev
```

then compiled:
```
./autogen.sh

./configure \
--enable-plabel \
--enable-pgsql \
--enable-rabbitmq \
--enable-kafka \
--enable-geoipv2 \
--enable-jansson \
--enable-avro \
--enable-ndpi \
--enable-nflog 

make
sudo make install
```

running on LXC/LXD container with Ubuntu 19.10 Eoan as guest.

**Comment by paololucente** [comment]
Hi Fernando ( @fernandolcx ), the issue was introduced in July and should be now solved by 93c9204ff4189a7b22ecd7ee6e66e054f2baf304 . Can you give a try latest code and confirm it working for you? Paolo

**Comment by fernandolcx** [comment]
Still not working:

```
fernando@lab:~$ pmacct -s -p /tmp/out.pipe:

SRC_NET                                        PACKETS               BYTES
0.0.0.0                                        1218945               1358751505

lab@pmacct:~$ pmacct -V
pmacct IMT plugin client, pmacct 1.7.4-git (20191106-00)
 '--enable-plabel' '--enable-pgsql' '--enable-rabbitmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-avro' '--enable-ndpi' '--enable-nflog' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
```

Head lines of `nfacctd -f nfacctd.conf ` in debuf mode:
```
INFO ( default/core ): NetFlow Accounting Daemon, nfacctd 1.7.4-git (20191106-00)
INFO ( default/core ):  '--enable-plabel' '--enable-pgsql' '--enable-rabbitmq' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-avro' '--enable-ndpi' '--enable-nflog' '--enable-l2' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/home/lab/nfacctd.conf'.
INFO ( in/memory ): plugin_pipe_size=4096000 bytes plugin_buffer_size=352 bytes
INFO ( in/memory ): ctrl channel: obtained=212992 bytes target=93088 bytes
INFO ( out/memory ): plugin_pipe_size=4096000 bytes plugin_buffer_size=352 bytes
INFO ( out/memory ): ctrl channel: obtained=212992 bytes target=93088 bytes
DEBUG ( in/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 10.0.0.0 mask: 8
DEBUG ( in/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 100.64.0.0 mask: 10
DEBUG ( in/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 172.16.0.0 mask: 12
DEBUG ( in/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 192.168.0.0 mask: 16
DEBUG ( in/memory ): [/home/lab/networks.lst] IPv4 Networks Cache successfully created: 99991 entries.
DEBUG ( in/memory ): [/home/lab/networks.lst] v6 nh:  peer_asn: 0 asn: 0 net: :: mask: 0
DEBUG ( in/memory ): [/home/lab/networks.lst] v6 contains a default route
DEBUG ( in/memory ): [/home/lab/networks.lst] IPv6 Networks Cache successfully created: 32771 entries.
DEBUG ( in/memory ): allocating a new memory segment.
DEBUG ( default/core ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 10.0.0.0 mask: 8
DEBUG ( default/core ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 100.64.0.0 mask: 10
DEBUG ( default/core ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 172.16.0.0 mask: 12
DEBUG ( default/core ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 192.168.0.0 mask: 16
DEBUG ( default/core ): [/home/lab/networks.lst] IPv4 Networks Cache successfully created: 99991 entries.
DEBUG ( out/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 10.0.0.0 mask: 8
DEBUG ( out/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 100.64.0.0 mask: 10
DEBUG ( out/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 172.16.0.0 mask: 12
DEBUG ( out/memory ): [/home/lab/networks.lst] v4 nh:  peer asn: 0 asn: 0 net: 192.168.0.0 mask: 16
DEBUG ( out/memory ): [/home/lab/networks.lst] IPv4 Networks Cache successfully created: 99991 entries.
DEBUG ( default/core ): [/home/lab/networks.lst] v6 nh:  peer_asn: 0 asn: 0 net: :: mask: 0
DEBUG ( default/core ): [/home/lab/networks.lst] v6 contains a default route
DEBUG ( default/core ): [/home/lab/networks.lst] IPv6 Networks Cache successfully created: 32771 entries.
INFO ( default/core ): waiting for NetFlow/IPFIX data on :::2100
DEBUG ( out/memory ): [/home/lab/networks.lst] v6 nh:  peer_asn: 0 asn: 0 net: :: mask: 0
DEBUG ( out/memory ): [/home/lab/networks.lst] v6 contains a default route
DEBUG ( out/memory ): [/home/lab/networks.lst] IPv6 Networks Cache successfully created: 32771 entries.
DEBUG ( out/memory ): allocating a new memory segment.
DEBUG ( in/memory ): allocating a new memory segment.
OK ( in/memory ): waiting for data on: '/tmp/in.pipe'
DEBUG ( out/memory ): allocating a new memory segment.
OK ( out/memory ): waiting for data on: '/tmp/out.pipe'
```

**Comment by paololucente** [comment]
Thank you for the output in debug mode, it is the first thing i'd have asked you: from the output i can see that the bug is sorted out (before you would have had a different output, almost all zeroes). Please set 'nfacctd_net' and 'nfacctd_as' to 'longest' as by default it would take masks from NetFlow. Paolo

**Comment by fernandolcx** [comment]
Solved.
Thank you @paololucente.
