### ISSUE TITLE
Build fails with --disable-zmq and without zeromq dev

### ISSUE THREAD

**Issue by dsggregory** [pmacct/pmacct#376]
**Description**
Master build fails when zmq is not enabled. The bgp (bgp_lg.c) code includes zmq.h which might not exist.

**Version**
master

**Comment by paololucente** [comment]
Hi @dsggregory , thank you very much for reporting this. It is something introduced yesterday - apologies, like you said one should test WITHOUT ZMQ headers installed - and it should be fixed with the latest commit. Can you please give it a try and confirm it working for you? Paolo

**Comment by paololucente** [comment]
One moment @dsggregory , it needs one more kick.

**Comment by dsggregory** [comment]
Thanks for jumping on this so quickly. However, it still fails on master (a bit earlier in the build now). I should be checking against master, correct?

```
...
  CC       libpmbgp_la-bgp_lg.lo
In file included from bgp_lg.c:25:
./../zmq_common.h:23:10: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
          ^~~~~~~
compilation terminated.
make[2]: *** [Makefile:561: libpmbgp_la-bgp_lg.lo] Error 1
make[2]: Leaving directory '/root/pmacct/src/bgp'
```

**Comment by paololucente** [comment]
Hey @dsggregory , this last one was the right kick. Can you confirm now master working for you? Thanks, Paolo

**Comment by dsggregory** [comment]
Yes sir. That seems to have done the trick. Thanks Paolo!
