### ISSUE TITLE
no bytes counter on NSEL flows.

### ISSUE THREAD

**Issue by hyberdk** [pmacct/pmacct#502]
**Description**
when exporting from a Cisco ASA firewall the netflow is a bit different than from a "regular" device like a Cisco router or switch.

Im no expert, but as far as I can see Cisco ASA uses NSEL: NetFLow Secure Event Logging..

See this for further details: https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/guide/asa_netflow.html

On a high level plan there are multiple templates, and one single flow are always exported using multiple templates and each flow contains bi-directional information, whereas "regular" netflow has one record per direction.

The templates are as follows:

- Templates for Flow Creation Events
- Templates for Extended Flow Teardown Events
- Templates for Flow Denied Events
- Templates for Flow Teardown Events
- Templates for Flow Update Events
- Flow Update (at timer) and Flow Update (at teardown) Events
- Flow Update Records and Failover
- Flow Update Events and Clustering

each flow (or session if you will) through the firewall will have multiple templates depending on the timing and actions.

eg. a flow that are allowed will both have a 

- Flow Creation Event
- Flow Update Even (if long lived flow)
- Flow Teardown Event

Only update and teardown events have any counters, and they have two bytes and two packet:
- NF_F_FWD_FLOW_DELTA_BYTES (initatorOctets in Wireshark): 231
- NF_F_REV_FLOW_DELTA_BYTES (responderOctets in Wireshark): 232
- I dont know the official cisco name (initiatorPackets in Wireshark): 298
- I dont know the official cisco name (responderPackets in Wireshark): 299

![image](https://user-images.githubusercontent.com/3530739/116691465-1fa7c800-a9bb-11eb-9531-cb0ece1c60f7.png)

Anywho.. it basically boils down to: I dont have the in/out bytes counters when its being processed through nfacctd.

I guess I could use primitives to get the fields/counters and just ignore the "bytes" field that is always inserted, but I am not sure if that is the best aproach.. and what happens when an exporter sends the same flow using multiple templates, I assume its supported as I do see some data, but still..

Also further down the line it would be nice to be able to tell the difference between the differnet NSEL events like: creation, update, teardown, denied, etc. events eg. using the netflow data to parse out the data to a SIEM tool that needs to know the difference on the different templates for the same flow.

So, Paulo (@paololucente), what are your thoughts here??

I will be happy to send tcpdumps of the traffic

**Version**
https://github.com/pmacct/pmacct/commit/24b8650df2ef1ba0eb4c48b677a5d7acbf7a62be

**Comment by hyberdk** [comment]
I just realized that there has been multiple issues for ASAs in the past https://github.com/pmacct/pmacct/issues/205 https://github.com/pmacct/pmacct/issues/182 I should really have done the research before creating the issue, but like the others I see empty bytes field.. 

also, input on the different template for the same flow for SIEM would be interesting..

@paololucente I will email you a tcpdump of the traffic.

Im using the kafka/json for exports.

Thanks.

Esben

**Comment by bthresher183** [comment]
I'm also having this problem on Cisco Firepower FTP 1150's (Should be pretty close to ASA). I had this issue with asa-5510's but fixed with the tmp_asa_bi_flow: true Option. Doesn't seem to be working with these new firewalls.

{"event_type": "purge", "ip_src": "74.203.161.98", "ip_dst": "x.x.x.x", "packets": 0, "bytes": 0}
{"event_type": "purge", "ip_src": "96.45.245.234", "ip_dst": "x.x.x.x", "packets": 0, "bytes": 0}
{"event_type": "purge", "ip_src": "75.133.88.238", "ip_dst": "x.x.x.x", "packets": 0, "bytes": 0}

**Comment by hyberdk** [comment]
> I'm also having this problem on Cisco Firepower FTP 1150's (Should be pretty close to ASA).

heh.. yeah.. well, we have both, but since I'm not really good friends with those devices I just treat them as one type.. My firewall colleagues obviously does not agree, but usually I steer away from those. :-) We use almost all models in the ASA 55xx and some 4410 firepower.

ohh, I did see this on the pmacct.net page:

> Supports Cisco NEL for CGNAT scenarios and Cisco NSEL

Hopefully its just a simple thing to fix ;-)

**Comment by paololucente** [comment]
Hi Esben,

As we briefly touched base by email, i will have a fix soon, later tonight. This should address also your issue @bthresher183 .

Paolo

**Comment by hyberdk** [comment]
Hi Paolo,

thanks for the fix, there seems to be bytes and packet data coming back now.

```
{
  "event_type": "purge",
  "peer_ip_src": "10.10.4.102",
  "iface_in": 4,
  "iface_out": 32,
  "ip_src": "10.10.57.199",
  "ip_dst": "185.125.227.110",
  "port_src": 61768,
  "port_dst": 8080,
  "ip_proto": "6",
  "dscp": "0",
  "direction": "0",
  "appid": "0",
  "stamp_inserted": "2021-05-05 09:14:00",
  "stamp_updated": "2021-05-05 09:16:08",
  "packets": 14177,
  "bytes": 11918,
  "writer_id": "default_kafka/374"
}
```

Since the ASA sends bi-directional flow, are you just adding the in+out counters togetter in the "bytes" field? 

Or how does it work?

again thanks.

Esben

**Comment by paololucente** [comment]
Hi Esben,

Thanks for making me realise that probably the description of `tmp_asa_bi_flow` in CONFIG-KEYS was perhaps not one of the most clear. I have updated it now. See here: https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS#L3203-#L3212 . Does this help? If not, i should work to further improve it.

Paolo

**Comment by bthresher183** [comment]
> 
> 
> Hi Esben,
> 
> As we briefly touched base by email, i will have a fix soon, later tonight. This should address also your issue @bthresher183 .
> 
> Paolo

I am working on installing this to verify that my particular issue is fixed (Sorry for hijacking this). After downloading the zip, ./configure,make,make install. I am getting "/usr/local/sbin/nfacctd: error while loading shared libraries: libcdada.so.0: cannot open shared object file: No such file or directory" while running "/usr/local/sbin/nfacctd -D -f /etc/pmacct/wfwnfacctd.conf". Any ideas? Thanks!

**Comment by bthresher183** [comment]
Looks like that fixed it for me. Thank you for the quick fix!!

**Comment by hyberdk** [comment]
> Does this help? If not, i should work to further improve it.

yeah, its very clear now, thanks..

looking at the fix, its does not really solve my problem.. sure I have bytes data, but I cannot fit it into my database schema as it expects unidirectional flows and not bidirectional..

I though about splitting the bidirectional flow into two unidirectional flows, but looking ahead its like peeing in the pants, sure it feels warm and fuzzy for 10secs, but then its just cold and gross. The best way for me is most likely to develop a new schema for it and store it there, it would also mean that I can fit all the "nice" features like denies, and xlate tables etc.

million $ question is:

1. can I somehow detect that its a ASA/NSEL flow and push that to a different kafka topic, or do I need to setup new instances of the daemon and reconfigure my ASA's to a new port?

2. If I set tmp_asa_bi_flow to false again and then import the field 231 and 232 via primitives.lst can I get the data I want? I guess its just another field for your code and it would return the values correctly.. Then I can just ignore the "bytes" field..

I hope that makes sense..

Esben

**Comment by paololucente** [comment]
Hi Esben,

Surely i would not like the idea of leaving somebody with the pants wet. We can make your first point possible relatively quickly: currently there are heuristics to reckon NEL (not NSEL) data from the rest; NSEL can be easily distinguished due to its bi-flow nature. Idea would be to:

- run `pre_tag_map` where you assign a tag to NSEL traffic (and perhaps a different tag to "normal" flows); 
- add a new plugin for NSEL data and run both new and existing plugins with a `pre_tag_filter` to filter-in only relevant data;

I'll make progress and keep you posted, not a biggie to implement.

**Comment by hyberdk** [comment]
> - run pre_tag_map where you assign a tag to NSEL traffic (and perhaps a different tag to "normal" flows);
> - add a new plugin for NSEL data and run both new and existing plugins with a pre_tag_filter to filter-in only relevant data;

So just to carve it out in wet cardboard, this is not possible today, but something easily implemented?

If so, perhaps an implementation where a pre_tag_map can detect specific fields in the flow. Then I could just detect the  [firewallEvent](https://www.iana.org/assignments/ipfix/ipfix.xhtml#ipfix-firewall-event) and perhaps in conjunction with the [biflowDirection](https://www.iana.org/assignments/ipfix/ipfix.xhtml#ipfix-biflow-direction) it would be easy to separate different devices from each other. CheckPoints are being implemented, so I might also need to detect that and treat differently. :-)

> About your second point, unfortunately not that easy. I mean, surely you can do. But that would make bytes counters be a dimension rather than a measure (on which you make additions). In other words you will likely end up with one tuple per flow, probably not what you want.

mmmm, not entirely sure if I understand you correctly. I mean the devices only export once every minute, and currently nfacctd are configured to also export every minute, so would it make a difference? I get that if I re-configured nfacctd to aggregate over 5mins, it would see each 1min flow as unique and send those back.. 

there are obviously also flows without field 231/232, but they would be a different [firewallEvent](https://www.iana.org/assignments/ipfix/ipfix.xhtml#ipfix-firewall-event) type, so they would also be unique..

Or am I missing a bigger picture here?

Esben

**Comment by paololucente** [comment]
> So just to carve it out in wet cardboard, this is not possible today, but something easily implemented?

Right, i should have something ready towards end of the week.

> If so, perhaps an implementation where a pre_tag_map can detect specific fields in the flow. Then I could just detect the firewallEvent and perhaps in conjunction with the biflowDirection it would be easy to separate different devices from each other. CheckPoints are being implemented, so I might also need to detect that and treat differently. :-)

Yes, this is how i am moving forward.

> mmmm, not entirely sure if I understand you correctly. I mean the devices only export once every minute, and currently nfacctd are configured to also export every minute, so would it make a difference? I get that if I re-configured nfacctd to aggregate over 5mins, it would see each 1min flow as unique and send those back..

Under the current assumptions, yeah, all looks good.

Paolo

**Comment by paololucente** [comment]
Hi Esben,

This is also done. See 62e0c97485d1b71808e3ae4475c9d82e39fc9779, 4b054a555bdb61023063e19cc69158e986492eaf and 37477553285d5300b6f481b186167951a76d2855. Essentially:

- in your nfacctd config, you define a pre_tag_map as `pre_tag_map: /path/to/pretag.map`,
- in the map you define, say, a one liner like `set_tag=100 is_bi_flow=true`,
- in your nfacctd config, you instantiate the needed plugins and use `pre_tag_filter` to filter in/out data

Just let me know if you need further help with config, here or as always via unicast email.

Paolo

**Comment by hyberdk** [comment]
> Just let me know if you need further help with config

Hi Paulo, 

thanks for the new code, I can confirm that the `is_bi_flow=true` is working. was scratching my head as I could not get it to work until I realized that I had a typo in my config ;-)

Unfortunately, my troubles are not quite over yet.

I do see that the bidirectional flows are put into another kafka topic, but I still have some flows the the ASA that are send to the unidirectional flow topic.

the problem is that not all the templates from my ASA have the initiatorOctet and responderOctet fields

![image](https://user-images.githubusercontent.com/3530739/117659654-82a81480-b19c-11eb-8bd7-906d842d5af4.png)

This means that the flows that contains the bytes data go into one topic and other goes into the other topic.


here is my config:

```
root@flowapp01:/opt/nfacct# cat primitives.lst 
name=dscp       field_type=195  len=1   semantics=u_int
name=direction  field_type=61   len=1   semantics=u_int
name=appid      field_type=95   len=4   semantics=hex
name=transactionid      field_type=280  len=8   semantics=u_int
name=initiatorOctets    field_type=231  len=8    semantics=u_int
name=responderOctets    field_type=232  len=8    semantics=u_int
name=firewallEvent  field_type=233  len=1    semantics=u_int
```

```
root@flowapp01:/opt/nfacct# cat pretag.map 
set_tag=100 is_bi_flow=false
set_tag=200 is_bi_flow=true
```

```
root@flowapp01:/opt/nfacct# cat nfacctd.conf
!
!
! AUTOGENERATED FILE @ Mon May 10 12:34:00 UTC 2021 - PLEASE EDIT TEMPLATE INSTEAD
!
! Did you know CONFIG-KEYS contains the detailed list of all configuration keys supported ?
!
! General configs
!
debug: false
daemonize: false
!logfile: nfacct.log

!additional fields for netflow.
aggregate_primitives: /opt/nfacct/primitives.lst

!pretag to patch bi-directional flows and put that into another kafka topic
pre_tag_map: /opt/nfacct/pretag.map
!
! NetFlow/IPFIX daemon configs
!
nfacctd_port: 3011
! nfacctd_time_secs: true
! nfacctd_time_new: true


plugins: kafka[uni-flow], kafka[bi-flow]
!
pre_tag_filter[uni-flow]: 100
aggregate[uni-flow]: dscp,direction,appid,proto,src_host,dst_host,src_port,dst_port,in_iface,out_iface,peer_src_ip
kafka_output[uni-flow]: json
kafka_topic[uni-flow]: netflow-collector
kafka_refresh_time[uni-flow]: 60
kafka_history[uni-flow]: 1m
kafka_history_roundoff[uni-flow]: m
kafka_broker_host[uni-flow]: flowapp01
kafka_broker_port[uni-flow]: 9092
kafka_cache_entries[uni-flow]: 160000
! do not translate IP protocols into names, but keep ID
kafka_num_protos[uni-flow]: true

pre_tag_filter[bi-flow]: 200
aggregate[bi-flow]: dscp,direction,appid,proto,src_host,dst_host,src_port,dst_port,in_iface,out_iface,peer_src_ip,initiatorOctets,responderOctets,firewallEvent
kafka_output[bi-flow]: json
kafka_topic[bi-flow]: netflow-collector-biflow
kafka_refresh_time[bi-flow]: 60
kafka_history[bi-flow]: 1m
kafka_history_roundoff[bi-flow]: m
kafka_broker_host[bi-flow]: flowapp01
kafka_broker_port[bi-flow]: 9092
kafka_cache_entries[bi-flow]: 160000
! do not translate IP protocols into names, but keep ID
kafka_num_protos[bi-flow]: true

root@flowapp01:/opt/nfacct# 
```

I think what I really need is to match IF "is_bi_flow = true" OR "firewallEvent != null"

I guess I could actually just do a IF "firewallEvent != null"

It would be nice to be able to check if a specific field exist in the flow and if such classify it accordingly.. I dont think that is possible today, right?

or something similar.. I hope that makes sense.

Esben

**Comment by hyberdk** [comment]
Hi Paulo,

I'm not sure that I understand the documentation.

How do I add additional information in `sample_type=event`

I mean, are they not all events? 

Esben
